### ISSUE TITLE
documentation about user.estimator

### ISSUE THREAD

**Issue by jkurle** [gsucarrat/gets#10]
Many functions in the package allow for user estimators, for example the `arx()` function and `getsm()` through the arx object. It is apparent from the source code that the user supplied functions can be run in a user specified environment, which can avoid potential scoping issues. However, this detail cannot be found in the documentation. I think it would be good to make this option explicit in the documentation. What do you think?

Since it does not concern the code, I do not know how to change it.

**Comment by moritzpschwarz** [comment]
My understanding is that you can edit the description here: https://github.com/gsucarrat/gets/tree/master/gets-devel/man

**Comment by jkurle** [comment]
Thanks for the explanation, Moritz! If everyone agrees that this change makes sense - maybe there are reasons for keeping it hidden from users - I can add a short note to the documentation about the environment element of the argument.

**Comment by gsucarrat** [comment]
Jonas, I am impressed you discovered the existence of the 'envir' argument! I will update the documentation. Note that it can be present in all functions where a user-defined facility is present: user-estimation, user-diagnostics and user-defined goodness-of-fit function, and this is not limited to arx(), getsm(), getsv() and isat(). All this is implemented via a 'do.call()' command, which has an argument 'envir' whose default is parent.frame(). The value of parent.frame() depends on when it is called, which complicates things! I think the 'envir' option should therefore only be briefly mentioned in the documentation. However, in my paper on user-specification possibilities, which ideally should become a vignette of the package, the 'envir' option should proably play a greater part. Note that, currently, it is already mentioned there at appropriate places: https://mpra.ub.uni-muenchen.de/96653/
