### ISSUE TITLE
Organisation of Github

### ISSUE THREAD

**Issue by gsucarrat** [gsucarrat/gets#16]
Following our online meeting 4 August 2020, I aim at uploading version 0.25 to CRAN on the morning of 11 August. Then, once the update is confirmed by CRAN, I will re-organise the Github-files. This will probably take place on the 11th or 12th of August.

**Comment by moritzpschwarz** [comment]
Just for your information, I have just deleted all branches except for the master branch. This allows you then to start fresh when you create the branches, as we discussed in the email.

**Comment by gsucarrat** [comment]
Excellent! I just created a 'devel' (development) branch. This is what you and J-bat have asked for, right?

**Comment by moritzpschwarz** [comment]
> Excellent! I just created a 'devel' (development) branch. This is what you and J-bat have asked for, right?

Yes, exactly, thanks! 
This allows us now to create sub-branches for the development of individual issues/features.

Do I remember correctly that you will also re-arrange the directory structure?

**Comment by gsucarrat** [comment]
I think the answer to the question "...re-arrange the directory structure?" is "no";) What I meant to say is that the source-code is now located in the folder gets/R/, and not in the root as before. I have also re-named the package-folder to "gets" (earlier it was called "gets-devel"). The new name of the folder and the new location of the source-code means the naming and structure of the package folder is essentially equal to how CRAN expects the package-folder to look like. Put differently, I have removed some idiosyncracies introduced by me that were useful at the time of introduction;)

**Comment by moritzpschwarz** [comment]
That's great, this will do! This will now allow us to implement automatic testing :)
