### ISSUE TITLE
Error introduced to getsFun() in version 0.24

### ISSUE THREAD

**Issue by moritzpschwarz** [gsucarrat/gets#17]
As mentioned before, the error message `singular matrix 'a' in solve` is quite frustrating, because as a user it is very difficult to know where the error lies that prevents the matrix to be inverted (e.g. could be a tolerance issue with near-perfect collinearity) 

I share a small example where `arx` works fine but `getsm` does not. 
The file is attached to this issue.
[data.zip](https://github.com/gsucarrat/gets/files/5048461/data.zip)

```{r}
library(gets)
library(tidyverse)
df <- read.csv("~/df_example_gets_error.csv")

dep_var = "total"
fixed_effects = "month"
theory_variables = c("WTI","discount")
tolerance = 1e-15
diagnostic_target_value = 0.01
selection_target_value = 0.05
select_over = c("L1.total", "L1.WTI", "L1.discount", "L1.alberta_incorporations", 
                "L1.non_alberta_incorporations", "L1.bankr_corporate", "L1.bankr_personal", 
                "L1.retail_trade_seasonally_adjusted", "L1.domestic_export_total_of_all_merchandise", 
                "D1.WTI", "D1.discount", "D1.alberta_incorporations", "D1.non_alberta_incorporations", 
                "D1.bankr_corporate", "D1.bankr_personal", "D1.retail_trade_seasonally_adjusted", 
                "D1.domestic_export_total_of_all_merchandise", "D1.L1.total", 
                "D1.L1.WTI", "D1.L1.discount", "D1.L1.alberta_incorporations", 
                "D1.L1.non_alberta_incorporations", "D1.L1.bankr_corporate", 
                "D1.L1.bankr_personal", "D1.L1.retail_trade_seasonally_adjusted", 
                "D1.L1.domestic_export_total_of_all_merchandise", "D1.L2.total", 
                "D1.L2.WTI", "D1.L2.discount", "D1.L2.alberta_incorporations", 
                "D1.L2.non_alberta_incorporations", "D1.L2.bankr_corporate", 
                "D1.L2.bankr_personal", "D1.L2.retail_trade_seasonally_adjusted", 
                "D1.L2.domestic_export_total_of_all_merchandise", "D1.L3.total", 
                "D1.L3.WTI", "D1.L3.discount", "D1.L3.alberta_incorporations", 
                "D1.L3.non_alberta_incorporations", "D1.L3.bankr_corporate", 
                "D1.L3.bankr_personal", "D1.L3.retail_trade_seasonally_adjusted", 
                "D1.L3.domestic_export_total_of_all_merchandise", "D1.L4.total", 
                "D1.L4.WTI", "D1.L4.discount", "D1.L4.alberta_incorporations", 
                "D1.L4.non_alberta_incorporations", "D1.L4.bankr_corporate", 
                "D1.L4.bankr_personal", "D1.L4.retail_trade_seasonally_adjusted", 
                "D1.L4.domestic_export_total_of_all_merchandise", "D1.L5.total", 
                "D1.L5.WTI", "D1.L5.discount", "D1.L5.alberta_incorporations", 
                "D1.L5.non_alberta_incorporations", "D1.L5.bankr_corporate", 
                "D1.L5.bankr_personal", "D1.L5.retail_trade_seasonally_adjusted", 
                "D1.L5.domestic_export_total_of_all_merchandise", "D1.L6.total", 
                "D1.L6.WTI", "D1.L6.discount", "D1.L6.alberta_incorporations", 
                "D1.L6.non_alberta_incorporations", "D1.L6.bankr_corporate", 
                "D1.L6.bankr_personal", "D1.L6.retail_trade_seasonally_adjusted", 
                "D1.L6.domestic_export_total_of_all_merchandise", "month_10", 
                "month_11", "month_12", "month_2", "month_3", "month_4", "month_5", 
                "month_6", "month_7", "month_8", "month_9", "iis_14")



# ARX runs without a problem
arx_model <- arx(y = df  %>% select(all_of(paste0("D1.",dep_var))) %>% pull,
                 mxreg = df %>% select(all_of(select_over)) %>% as.matrix,
                 mc=T,
                 tol=tolerance)

# Create A Keep Vector
keep_vector <- df %>% 
  select(all_of(select_over)) %>% names

keep_vector_numeric <- grep(fixed_effects,keep_vector)
keep_vector_numeric <- append(keep_vector_numeric,grep(paste0(theory_variables,collapse ="|"),keep_vector))

# This fails with Error in qr.solve(mR %*% gum.varcovmat %*% t(mR), tol = tol) : 
# singular matrix 'a' in solve

# the function that actually fails is getsFun()

selection <- getsm(object = arx_model, 
                   t.pval = selection_target_value,
                   
                   ar.LjungB = list(lag = NULL, pval = diagnostic_target_value),
                   arch.LjungB = list(lag = NULL, pval = diagnostic_target_value), 
                   normality.JarqueB = diagnostic_target_value, # Jarque and Bera (1980) test for non-normality
                   do.pet = TRUE, # Parsimonious Encompassing Test 
                   
                   keep = keep_vector_numeric + 1, # +1 because of mc=T
                   plot = F)
```

**Comment by moritzpschwarz** [comment]
Even though I think this particular error should still be tackled, I will rename this issue because this code works with gets version 0.23. 
So I believe this is a bug that was introduced in version 0.24. 
Worth checking before we upload 0.25 to CRAN!

**Comment by moritzpschwarz** [comment]
I have managed to identify where the code fails - it's only when I select `do.pet = TRUE`

https://github.com/gsucarrat/gets/blob/a5130719df717735ba0bb88c294a32e922120b68/gets-base-source.R#L1147

I *think* the reason for this is that the `tol` argument that is set in `arx` object is not forwarded to the internal `getsFun`. 

To illustrate: 
In **Version 0.23**, the `tol` argument from the `arx` object was extracted here:
https://github.com/gsucarrat/gets/blob/a5130719df717735ba0bb88c294a32e922120b68/0-past-versions/0.23/gets-base-source.R#L3558

And then forwarded to the `ols` command here:
https://github.com/gsucarrat/gets/blob/a5130719df717735ba0bb88c294a32e922120b68/0-past-versions/0.23/gets-base-source.R#L3630-L3631

In Version 0.24, however, the new `getsFun` within `getsm` is not invoked with a `tol` argument:
https://github.com/gsucarrat/gets/blob/a5130719df717735ba0bb88c294a32e922120b68/gets-base-source.R#L4215-L4223

Which means that the default setting of `tol` is used in `getsFun`, which is `1e-7`; ignoring what was set in the `arx` object:
https://github.com/gsucarrat/gets/blob/a5130719df717735ba0bb88c294a32e922120b68/0-past-versions/0.23/gets-base-source.R#L607-L615

**Solution**
I think the solution would be very easy: extract the `tol` argument from the `arx` object and then specify it when invoking the new `getsFun`. 

**Questions** 
- @gsucarrat do you want me to create a pull request for this? 
- I presume this would be an issue for `getsv` as well, right? The argument is missing there as well. Anywhere else?

**Comment by gsucarrat** [comment]
The 'tol' argument in arx() is used when 'user.estimator=NULL' (the default) for detecting linear dependence in OLS estimation. By contrast, the 'tol' argument in getsFun() is used in the Wald-test - hence the error when 'do.pet=TRUE'. From what you are saying, it seems the error is more likely due to the recent changes in getsm() rather than getsFun(). I will have a detailed look at it...

**Comment by moritzpschwarz** [comment]
Great thanks!
Indeed, I have encountered the `tol` argument in `arx` fair number of times, as my data frequently suffers from linear dependence. Hence my interest in it :)

**Comment by gsucarrat** [comment]
In the newest build (11 August 2020, version 0.25), getsm() and getsv() have acquired the new argument 'tol'. So changing it to a more tolerant level should solve your problems if the cause lies in the Wald-test.

**Comment by moritzpschwarz** [comment]
> In the newest build (11 August 2020, version 0.25), getsm() and getsv() have acquired the new argument 'tol'. So changing it to a more tolerant level should solve your problems if the cause lies in the Wald-test.

Thanks very much, indeed this solves the problem! 
I will close this issue now.
