### ISSUE TITLE
isat does not count number of estimations during model selection

### ISSUE THREAD

**Issue by jkurle** [gsucarrat/gets#40]
Following issue #39, I wanted to implement a warning in my estimations that tells me when `isat()` has actually not done any selection. I thought the easiest would be to give a warning when the entry `no.of.estimations` of the returned object is equal to 1.

However, `isat()` does not count the number of estimations properly. Example:

```r
data(Nile)
selection <- isat(Nile, sis=TRUE, iis=TRUE, plot=TRUE, t.pval=0.005)
print(selection$no.of.estimations) # returns 1
```

The reason is the following: `isat()` does not have a counter across the internal calls of `getsFun()`. In fact, in a final step, all retained indicators are added for a final call of `getsFun()`. This is again treated as a "GUM" (see issue #39 again), so if all the final indicators are jointly significant, no selection is undertaken and the final `no.of.estimations` is equal to 1.

https://github.com/gsucarrat/gets/blob/7c7ac53aab229cd5f9ad174bcb5d2b0d14cf7661/gets/R/gets-isat-source.R#L561-L562
https://github.com/gsucarrat/gets/blob/7c7ac53aab229cd5f9ad174bcb5d2b0d14cf7661/gets/R/gets-isat-source.R#L617

Resolving this issue shouldn't be too much of a problem. We would need a counter that keeps track of and sums up the number of estimations across all block searches. The hardest part is the block search that is done via `lapply()` and `parLapply()`, which call the internally defined `ISblocksFun()`. A quick but possibly dirty solutions would be to manipulate some counter variable outside the scope of the apply construct using `<<-`.

**Comment by jkurle** [comment]
The previous suggestion of testing whether `no.of.estimations` is equal to 1 does not work since even when no selection is undertaken, more than one model is estimated and the number of models estimated differs by the specification of the `isat()` arguments. The following suggested solution is flexible enough to account for this and I intend to use it at least as a hot fix.

I have implemented some changes in `isat()` so that it counts the total number of estimations and stores them as the element `no.of.estimations` in the returned object. Furthermore, I have added a counter for how often `getsFun()` is being called from within `isat()`. This is stored in a new list element called `no.of.getsFun.calls` and allows us to tell whether any selection has been done.

The reasoning is as follows. `isat()` calls `getsFun()` several times:

1) for each type of indicator (IIS, SIS etc.):
   a) each block calls `getsFun()` once and the full block (+original regressors) is seen as "GUM"
   b) __if any indicator of that type has been retained__: call `getsFun()` again to select over them
2) combine all indicators that had been retained and call `getsFun()` to select over them

If the "GUM" of each block fails the diagnostics then no indicator of that type is retained an 1b) is not even reached. Suppose we have 100 observations and run IIS in blocks of 25 indicators each but the diagnostics fail in each case. Then we have __4 calls__ for IIS (1a), __no call__ to select over the union of retained impulses (1b), plus a __final call__ in (2) without any indicators since none were retained. In total, `no.of.getsFun.calls` = `no.of.estimations` = 5. These two counts being equal should occur if and only if no selection was done.

As a comparison, using the above example of the Nile data without any diagnostics gives `no.of.getsFun.call` = 10 (4 times for SIS and 4 times for IIS (1a), selecting over the retained steps but not over impulses because none were retained initially (1b), selecting over all indicators (2), which is only steps). In contrast, we have `no.of.estimations` = 4770.

The following commits from my fork implement this procedure: 95e07d7c5a1ce5b78a6fa817263086fd50f8b62a, 00d32f5ef250bfb45af97df5b32c8406265b42ce, 9211a4aa54d3f1f6ed7a64785b9d1bbbd91f51d8.

**Comment by moritzpschwarz** [comment]
Awesome that you have already come up with fixes Jonas - could you commit them to a branch here by any chance? Then we can analyse it from there.

**Comment by jkurle** [comment]
> 
> 
> Awesome that you have already come up with fixes Jonas - could you commit them to a branch here by any chance? Then we can analyse it from there.

I've made a pull request from my fork, should work equally well for comparisons. All checks pass.
