### ISSUE TITLE
standardise diagnostic test arguments

### ISSUE THREAD

**Issue by jkurle** [gsucarrat/gets#41]
Hi again,

I noticed an inconsistency how the diagnostic test arguments are specified in `isat()`/`getsm()`/`getsv()` versus `getsFun()`. When standardising, needs some care in how arguments are passed on since, for example, `isat()` calls `getsFun()`. Otherwise should be easy for the next update.

argument | `isat()` | `getsm()`/`getsv()` | `getsFun()`
-----------|-------|--------------------|------------
`ar.LjungB` (to turn on) | list with lag and pval | list with lag and pval | vector with two entries
`arch.LjungB` (to turn on) | list with lag and pval | list with lag and pval | vector with two entries

https://github.com/gsucarrat/gets/blob/7c7ac53aab229cd5f9ad174bcb5d2b0d14cf7661/gets/man/isat.Rd#L40-L41
https://github.com/gsucarrat/gets/blob/7c7ac53aab229cd5f9ad174bcb5d2b0d14cf7661/gets/man/getsm.Rd#L35-L36
https://github.com/gsucarrat/gets/blob/7c7ac53aab229cd5f9ad174bcb5d2b0d14cf7661/gets/man/getsFun.Rd#L27-L28

**Comment by jkurle** [comment]
Sure, that shouldn't be a problem. We need to agree internally how it is handled but given the user input, a list could easily be translated into a vector (since both entries are numeric) and vice versa. The documentation, however, should mention both possibilities.

**Comment by gsucarrat** [comment]
Well spotted! In getsm() and getsv() I will, when I get there, change the arguments to vectors, while - internally - allow for lists() for backwards compability. We can mention this in the documentation.
