### ISSUE TITLE
Standardise Intercept behaviour in arx and isat

### ISSUE THREAD

**Issue by moritzpschwarz** [gsucarrat/gets#6]
Currently there are different default behaviours for `isat` and `arx` whether an intercept (`mc`) should be included.

https://github.com/gsucarrat/gets/blob/d654339dbd2ad062ad00be54a095e3a99d9d8193/gets-base-source.R#L1306

https://github.com/gsucarrat/gets/blob/d654339dbd2ad062ad00be54a095e3a99d9d8193/gets-isat-source.R#L38

I would argue that the default behaviour should be the same in the same package.

Perhaps the least disruptive reaction would be to remove the default behaviour altogether for the `mc` value. That would force the researcher to make the choice explicitly.

But this should probably be discussed.

**Comment by jkurle** [comment]
I agree that it might be nicer if the default behaviour was consistent across functions in the same package. From my own experience, indicator selection often works better when an intercept is included and including it is not very costly. However, it might be more common in autoregressive models to not include an intercept? So maybe there are reasons for this difference.

Connected to this intercept issue, I was wondering whether isat() should be adapted to allow for selection over an intercept. The intercept is a special case of a step ranging from the first to last observation. However, it is currently dropped from the selection set, in line 205: https://github.com/gsucarrat/gets/blob/d654339dbd2ad062ad00be54a095e3a99d9d8193/gets-isat-source.R#L200-L205
I think dropping it is the right decision when a user is sure they don't want an intercept in the model. However, the user might instead want to find out during model selection (to serve both use cases, a new function argument would be necessary, I think).

**Comment by gsucarrat** [comment]
The default mc=FALSE of arx() was conceived more than 10 years ago when it was intended to model financial returns. In that context it often makes sense to set the intercept to zero. Now that arx() is used more generally, I guess we can reconsider that default. As for isat(), which was conceived about 6 years ago, we concluded that the appropriate default was mc=TRUE. I do not think we should change that. Regarding whether to allow for selection over the intercept in isat(), I think we should, but that decision lies with Felix/James (I have on earlier occasions also proposed this). Jonas, I suggest you open a separate issue on this.

**Comment by moritzpschwarz** [comment]
@jjreade and @fpretis any opinions on whether we should change the default in `arx` so that the intercept is included by default? 

Or that it is a required input by the user (i.e. for now there is no default)?

**Comment by jjreade** [comment]
I'm happy with changing the default, it's always bugged me a little that there's the inconsistency between arx and isat :-)

**Comment by gsucarrat** [comment]
Following our discussion in the online-meeting 4 August 2020, let me suggest that we aim at changing the default 'mc' argument to 'TRUE' in arx() in version 0.26 (mid-September) of 'gets'.

**Comment by moritzpschwarz** [comment]
> Following our discussion in the online-meeting 4 August 2020, let me suggest that we aim at changing the default 'mc' argument to 'TRUE' in arx() in version 0.26 (mid-September) of 'gets'.

Should we start implementing this now then? Maybe with a warning message? 
@gsucarrat @jkurle

**Comment by gsucarrat** [comment]
I tried implementing the new default, but it induced an error when using the `getsm().` Specifically, it was the example in as.lm.Rd that revealed the issue:

`set.seed(123)
y <- rnorm(30)
arxmod <- arx(y, mc=TRUE, ar=1:3)
as.lm(arxmod)

##from 'gets' to 'lm':
getsmod <- getsm(arxmod, keep=1)`

**Comment by moritzpschwarz** [comment]
> I tried implementing the new default, but it induced an error when using the `getsm().` Specifically, it was the example in `as.lm.Rd` that revealed the issue:
> 
> `set.seed(123)`
> `y <- rnorm(30)`
> `arxmod <- arx(y, mc=TRUE, ar=1:3)`
> `as.lm(arxmod)`
> 
> `##from 'gets' to 'lm':`
> `getsmod <- getsm(arxmod, keep=1)`
> 
> Having looked into it, it seems changing the new default to `mc=TRUE` is not as straightforward as we thought. So I am afraid we will have to postpone it.

I cannot replicate this I'm afraid - should we open up a new branch and then test where the error comes from?

**Comment by gsucarrat** [comment]
To replicate the error the arx() function needs to be changed. Specifically, you need to modify the default of the 'mc' argument by changing it to 'TRUE'. While I have not verified it, I am pretty sure the source of the error is getsm(). Once we sort that out, then we also need to check that the new default does not affect predict.arx()/predict.gets()/predict.isat(). Alternatively, they might need modification to handle the new default correctly. Feel free to open a new branch.

**Comment by moritzpschwarz** [comment]
Thanks @gsucarrat 

I think I found the issue: 

In this example, in `getsm`, when all models are selected, it runs an `arx` command again. 
So far, we had not specified an `mc` argument for this - meaning it would revert to the default, which was `mc=FALSE`. This is relevant in the special case where the intercept `mconst` was selected as a relevant regressor in the selection procedure above. Given that we have now changed the default, `mc` would get the argument `TRUE` and would add another column with `1`s - additional to the selected column with `1`s that came from `mconst`.

The old version looks like this: 
https://github.com/gsucarrat/gets/blob/ed80a74fd36123aa63aefc19af2d85d26adc519b/gets/R/gets-base-source.R#L4447-L4455


The solution is to set `mc=FALSE` as an argument within the `getsm` function - as there we don't care about the `arx` default, because `getsm` has already made this decision for us.  

**Therefore I have set `mc=FALSE` within the `arx` call within `getsm` and `getsv` for both the standard and the user-defined estimator.**

The relevant lines are: 
`getsm` standard
https://github.com/gsucarrat/gets/blob/e4031a26a3f407fc4ea7e43d5f6a003022ecc5fa/gets/R/gets-base-source.R#L4447-L4455

`getsm` user-estimator
https://github.com/gsucarrat/gets/blob/e4031a26a3f407fc4ea7e43d5f6a003022ecc5fa/gets/R/gets-base-source.R#L4461-L4465

and `getsv`
https://github.com/gsucarrat/gets/blob/e4031a26a3f407fc4ea7e43d5f6a003022ecc5fa/gets/R/gets-base-source.R#L4620-L4625


I have also added the warning: 
**"Warning: Default argument for mc (Intercept) was changed in gets version 0.27. Before it was mc=FALSE, now it is mc=TRUE. Suppress warning by directly specifying the mc argument."**
which is displayed, when someone does not specify the `mc` argument. We can remove this after a while, but for now it might be good to keep.

Everything is visible in the diff for the relevant `intercept` branch. 
**I have not yet run the tests on this though.**

**Comment by gsucarrat** [comment]
Thanks for looking into this!! But I am afraid things may not be that straightforward... We also need to look into how predict.arx() handles the change of default. This may also have consequences for predict.gets() and predict.isat() too, which both rely on predict.arx().

**Comment by moritzpschwarz** [comment]
> Thanks for looking into this!! Your insights will be very useful once I start implementing the change. We also need to look into how predict.arx() handles the change of default. This may also have consequences for predict.gets() and predict.isat(), since they both rely on predict.arx().

Spot on G-man! Indeed, `predict.arx` needed changes as well and the automatic testing confirmed your suspicions. 

I have tried to implement all this now in the new branch, the pull request is here: #32  
You can see all changed files here: https://github.com/gsucarrat/gets/pull/32/files

# Suggested changes of pull request #32 are in:

1. the `arx` function (just changed the default)
2. the `regressorsMean` function (just changed the default)
3. A few documentation files (`.Rd`) - especially some examples in there
4. A few of the tests (e.g. test that used to be `arx(y)` now need to be `arx(y, mc=FALSE)` to get the same behaviour.
5. The `predict.arx` and the `predict.gets` & `predict.isat` function: here when the intercept was not retained, the default was always to set it to `NULL` in a new call that was passed to `predict.arx`. Now I set it to `FALSE` rather than `NULL`. See below for an error that is in the current code because of this.
6. The `getsm`, `getsv` and `isat` function, because they all use the `arx` command - see the comments where we discuss this above






## Appendix: 
Error in the current package version that would also be resolved with this: 

```r
##Simulate from an AR(1):
set.seed(123)
y <- arima.sim(list(ar=0.4), 70)

##estimate an AR(2) with intercept:
explicit <- arx(y, mc=FALSE, ar=1:2)
implicit <- arx(y, ar=1:2)

identical(coef(explicit),coef(implicit))
identical(residuals(explicit),residuals(implicit))

# These should be the same also for predictions
set.seed(123)
predict(implicit,n.ahead = 10, plot=TRUE)

set.seed(123)
predict(explicit,n.ahead = 10, plot=TRUE)
```

The reason for this is here where the `mc` element is only checked whether it is `NULL` or not, but not if it is `TRUE` or `FALSE`.
https://github.com/gsucarrat/gets/blob/47ba31ce4bbd37164081f2f126b06dc5599370d0/gets/R/gets-base-source.R#L3145-L3151

My suggestion (already in #32) would be: 
https://github.com/gsucarrat/gets/blob/6d31556cb86b30dd40508157c460bca87919bd24/gets/R/gets-base-source.R#L3147-L3154

Note the `is.null` is not reversed anymore, because the default state for `mc` is now `TRUE`.

**Comment by gsucarrat** [comment]
As of version 0.28, `mc = TRUE` is now the default in `arx()`.
