### ISSUE TITLE
isat does not deal with perfectly collinear variables correctly 

### ISSUE THREAD

**Issue by moritzpschwarz** [gsucarrat/gets#62]
This is an issue that occurs when the gum contains perfectly collinear variables.

Here an example. These should be identical: 

```r
library(gets)
data(hpdata)
y <- zooreg(hpdata$GCQ, 1959, frequency=4)
dlogy <- diff(log(y))
x <- zooreg(hpdata$GYDQ, 1959, frequency=4)
xmatrix <- as.zoo(ts(data.frame(GYDQ = diff(log(x))), start = index(dlogy)[1], end = index(dlogy)[144], frequency = 4))

a <- isat(dlogy, mxreg=xmatrix$GYDQ, iis=TRUE, sis = FALSE, t.pval =0.05, plot = TRUE)

xmatrix$GYDQ_lincom <- xmatrix$GYDQ * 4

b <- isat(dlogy, mxreg=xmatrix, iis=TRUE, sis = FALSE, t.pval =0.05, plot = TRUE)

a
b
```
But a and b are not identical. b contains a linear combination that should be dropped. Yet different IIS variables are retained.

**Comment by gsucarrat** [comment]
Could you illustrate the error with simulated data instead? Because empirical data and data frames are notorious in generating spurious errors:)

**Comment by moritzpschwarz** [comment]
For completeness, as the PR #63 has already been merged. Before the merge, this did not give equal results:

```r
set.seed(123)
y <- rnorm(100)
xvar <- rep(2,100) # perfectly collinear with intercept mc
isat(y, mc = TRUE, mxreg = xvar)

isat(y, mc = TRUE)
```
