### ISSUE TITLE
Adjusting the intercept of the ISAT output to zero.

### ISSUE THREAD

**Issue by namtran6701** [gsucarrat/gets#71]
I was wondering if there is a way to force the intercept of this output to 0. 

isat(y = df$META, xreg = df$SPY)

**Comment by SantiagoD999** [comment]
If you want to exclude the intercept in the estimation, you could set mc=FALSE. That is:
isat(y = df$META, xreg = df$SPY,mc=FALSE)

**Comment by jforest443** [comment]
I don't want to exclude the intercept. I want to restrict it to be equal to zero. That is different that excluding a regressor to restrict the coeff to zero. 

Anyone know how to restrict the intercept in Gets?

**Comment by moritzpschwarz** [comment]
Hi all, 

coming at this not being a specialist in those types of estimation - but you could achieve something like this with the `nls` command. 

If you want to use methods like those, you can use a `user.estimator` that you can modify as you like. @gsucarrat has written a paper about this [here](http://www.sucarrat.net/research/user-specified-gets-and-isat.pdf). 

To get you started, consider this: 

```r
library(gets)

# create some random data
y <- rnorm(100)
xvars <- matrix(rnorm(100 * 5), ncol = 5)
colnames(xvars) <- paste0("x", 1:ncol(xvars))

# create a user-defined estimator
nls_fun <- function(y, x, ...){

  # Use formula nls (note we need to specify the coefficients as well in the formula, different to lm - here each coefficient is c and then a number)
  form <- as.formula(paste0("y ~ ",paste0("c", 1:ncol(x), " * ", colnames(x), collapse = " + ")))

  dat <- data.frame(y, x)

# set the starting and upper/lower bound values for each coefficient
  start_vec <- rep(0, ncol(x))
  upper_vec <- rep(Inf, ncol(x)) 
  lower_vec <- rep(-Inf, ncol(x)) 
  
  names(start_vec) <- paste0("c", 1:ncol(x)) 
  names(upper_vec) <- paste0("c", 1:ncol(x)) 
  names(lower_vec) <- paste0("c", 1:ncol(x)) 
 
  upper_vec["c1"] <- 0 # set the intercept upper bound to 0
  lower_vec["c1"] <- 0 # set the intercept lower bound to 0

  fit1 <- nls(formula =  form,
              data = dat, 
              start = start_vec, 
              lower = lower_vec,
              upper = upper_vec,
              algorithm = "port") 
  
  
  nls_coef <- coef(fit1)
  names(nls_coef) <- colnames(x)
  nls_k <- length(coef(fit1))
  nls_n <- length(summary(fit1)$resid)
  nls_vcov <- vcov(fit1)
  colnames(nls_vcov) <- colnames(x)
  row.names(nls_vcov) <- colnames(x)
  
  nls_loglik <- as.numeric(logLik(fit1))
  nls_df <- summary(fit1)$df[2L]
  
  out <- list()
  out$coefficients <- nls_coef
  out$k <- nls_k
  out$n <- nls_n
  out$vcov <- nls_vcov
  out$logl <- nls_loglik
  out$df <- nls_df
  return(out)
}

# and then we can use this function within the gets functions
arx(y = y, mxreg = xvars, mc = TRUE, user.estimator = list(name = "nls_fun"))

# or even in isat: 
isat(y = y, mxreg = xvars, mc = TRUE, user.estimator = list(name = "nls_fun"))
```

## Note 1
I'm really not an expert in this type of estimation: so please think about whether the model selection (based on the LogLikelihood) would have the same interpretation given the chosen information criterion. So please double check that template

## Note 2
For some seeds, the `isat` command fails to converge. Please think about what you want the algorithm to do if it does not converge. I wouldn't know. 


Happy to help further if you need any help

**Comment by namtran6701** [comment]
> Hi all,
> 
> coming at this not being a specialist in those types of estimation - but you could achieve something like this with the `nls` command.
> 
> If you want to use methods like those, you can use a `user.estimator` that you can modify as you like. @gsucarrat has written a paper about this [here](http://www.sucarrat.net/research/user-specified-gets-and-isat.pdf).
> 
> To get you started, consider this:
> 
> ```r
> library(gets)
> 
> # create some random data
> y <- rnorm(100)
> xvars <- matrix(rnorm(100 * 5), ncol = 5)
> colnames(xvars) <- paste0("x", 1:ncol(xvars))
> 
> # create a user-defined estimator
> nls_fun <- function(y, x, ...){
> 
>   # Use formula nls (note we need to specify the coefficients as well in the formula, different to lm - here each coefficient is c and then a number)
>   form <- as.formula(paste0("y ~ ",paste0("c", 1:ncol(x), " * ", colnames(x), collapse = " + ")))
> 
>   dat <- data.frame(y, x)
> 
> # set the starting and upper/lower bound values for each coefficient
>   start_vec <- rep(0, ncol(x))
>   upper_vec <- rep(Inf, ncol(x)) 
>   lower_vec <- rep(-Inf, ncol(x)) 
>   
>   names(start_vec) <- paste0("c", 1:ncol(x)) 
>   names(upper_vec) <- paste0("c", 1:ncol(x)) 
>   names(lower_vec) <- paste0("c", 1:ncol(x)) 
>  
>   upper_vec["c1"] <- 0 # set the intercept upper bound to 0
>   lower_vec["c1"] <- 0 # set the intercept lower bound to 0
> 
>   fit1 <- nls(formula =  form,
>               data = dat, 
>               start = start_vec, 
>               lower = lower_vec,
>               upper = upper_vec,
>               algorithm = "port") 
>   
>   
>   nls_coef <- coef(fit1)
>   names(nls_coef) <- colnames(x)
>   nls_k <- length(coef(fit1))
>   nls_n <- length(summary(fit1)$resid)
>   nls_vcov <- vcov(fit1)
>   colnames(nls_vcov) <- colnames(x)
>   row.names(nls_vcov) <- colnames(x)
>   
>   nls_loglik <- as.numeric(logLik(fit1))
>   nls_df <- summary(fit1)$df[2L]
>   
>   out <- list()
>   out$coefficients <- nls_coef
>   out$k <- nls_k
>   out$n <- nls_n
>   out$vcov <- nls_vcov
>   out$logl <- nls_loglik
>   out$df <- nls_df
>   return(out)
> }
> 
> # and then we can use this function within the gets functions
> arx(y = y, mxreg = xvars, mc = TRUE, user.estimator = list(name = "nls_fun"))
> 
> # or even in isat: 
> isat(y = y, mxreg = xvars, mc = TRUE, user.estimator = list(name = "nls_fun"))
> ```
> 
> ## Note 1
> I'm really not an expert in this type of estimation: so please think about whether the model selection (based on the LogLikelihood) would have the same interpretation given the chosen information criterion. So please double check that template
> 
> ## Note 2
> For some seeds, the `isat` command fails to converge. Please think about what you want the algorithm to do if it does not converge. I wouldn't know.
> 
> Happy to help further if you need any help

Thank you for your reply. Is there a way to replicate that customized nls function with lm?

**Comment by moritzpschwarz** [comment]
> Thank you for your reply. Is there a way to replicate that customized nls function with lm?

Just quickly coming back to this: using lm would of course not make it able to force the intercept to be 0, as in OLS this is not possible. Therefore it needs to be something like `nls`. Of course other functions might be able to do the same - they would then have to use the same logic to create a user-specified estimation method. 

Let us know if you need additional help with that - but for now (due to inactivity), I'll close this issue.
