### ISSUE TITLE
error when printing output of getsm in model with one (significant) regressor

### ISSUE THREAD

**Issue by jkurle** [gsucarrat/gets#9]
The following code throws an error:

```R
x <- rnorm(100,0,1)
u <- rnorm(100,0,1)
y <- 1 + 0.7 * x + u
model <- arx(y, mxreg=x)
selection <- getsm(model)
selection
```
Here, we have one significant regressor in the DGP and we select over it. Since `x` is (usually) significant in the GUM, no paths are searched and `getsFun()` (which is called by `getsm()`) returns the empty element `out$paths`. The same is true for `out$terminals`. Note that empty does not mean it is `NULL`. This is problematic for `print.gets()`:

https://github.com/gsucarrat/gets/blob/ebbd6b301dae9b7baf21a751bb85559c73d16549/gets-base-source.R#L4791-L4797

https://github.com/gsucarrat/gets/blob/ebbd6b301dae9b7baf21a751bb85559c73d16549/gets-base-source.R#L4803-L4808

The `for` loop starts at 1 and runs to 0. However, 0 is not a valid index and element 1 does not exist in an empty list.

**Comment by gsucarrat** [comment]
Could you be more specific about the error? Because when I rund your code (with set.seed) on the current development version, I do not get an error (apart from the lack of line-shift between the info-messages at the bottom):

set.seed(123)
x <- rnorm(100,0,1)
u <- rnorm(100,0,1)
y <- 1 + 0.7 * x + u
model <- arx(y, mxreg=x)
selection <- getsm(model)
selection

**Comment by jkurle** [comment]
I get the following error: "Error in x$paths[[i]] : subscript out of bounds", which is due to the fact that it tries to reference x$paths[[1]], which does not exist. I have just updated to the most recent development version 0.24 and I still get the error.

**Comment by gsucarrat** [comment]
Interesting, because I do not get any error... Which R version are you using? What OS? Did you install the development version under that R version and that OS?

**Comment by jkurle** [comment]
That's interesting indeed. I am using R version 4.0.2, Windows 10 x64. Yes, I installed the development version under this setup.

So you do get the whole output when you print the object "selection" to the console? Including the messages: "- 1-CUT not included (all non-keep regressors are significant)- All non-keep regressors significant in GUM" ? Or does your output stop early (i.e. after "Paths searched: ") without giving an error message?

**Comment by gsucarrat** [comment]
Yes, I get everything without absolutely any error. What is the build date of your gets-install? You can check this by typing:
library(gets)
help("gets-package")
There, the date should be "2020-07-24". Is that the case?

**Comment by jkurle** [comment]
I actually got an error when using `help("gets-package")`, so there must have been some issue with the installation (even though I was able to call `arx()` and `getsm()` without problems). After reinstalling, everything works now and I don't get the error anymore. Hence, the commit I made is not necessary anymore (but would also do no harm) - feel free to reject it in the pull request.
